### ISSUE TITLE
Can you add an overview / introduction to you README.md?

### ISSUE THREAD

**Issue by brymon68** [afryer/strava-react#1]
Hi, 

I came across your project researching ideas for a new project I will be writing in React. You have an insanely long README (which is great) but I think it would be a good idea to add an overview  / introduction section at the top so people can understand what your project actually does :)

Anywho, just a suggestion.

**Comment by afryer** [comment]
Hi, 

It is the generic readme from the react starter app which was the base of this. I will work on a proper readme at some point.
